### ISSUE TITLE
setup.sh missing a couple of package

### ISSUE THREAD

**Issue by bricewge** [giovannimanzoni/acmetools#2]
I had to manually install `unzip` and `wget` first to finish successfully `setup.sh`.

**Comment by giovannimanzoni** [comment]
Il 2015-12-10 14:42 bricewge ha scritto:

> I had to manually install unzip and wget first to finish successfully
> setup.sh.

Hello, Many thanks to give a try to my script ! Thanks, I will add them 
as soon as possible !

Thanks thanks thanks !

**Comment by giovannimanzoni** [comment]
Hello, it is fixed now :)
